variables:
  APP_PATH: "task_mongoDB"
  DOCKER_TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  NOME_DO_CONTAINER: task_app_container
  NOME_DA_REDE: app-network
  BIND_DE_PORTA: "8080:8080"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SPRING_PROFILES_ACTIVE: "test"
  MONGODB_URI: "mongodb://admin:admin@mongo:27017/workshop_mongo?authSource=admin"
  WAIT_TIMEOUT: "30"

stages:
  - test
  - build
  - deploy

Unit_Test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  only:
    - dev
  services:
    - name: mongo:latest
      alias: mongo
  script:
    - cd $APP_PATH
    - mvn verify -Dspring.data.mongodb.uri=$MONGODB_URI
    - mvn test
  artifacts:
    paths:
      - $APP_PATH/target/surefire-reports/

Build_Image:
  stage: build
  only:
    - dev
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd $APP_PATH
    - docker build -t $DOCKER_TAG_NAME .
    - docker push $DOCKER_TAG_NAME

Deploy_Container:
  stage: deploy
  only:
    - dev
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker network create $NOME_DA_REDE || true
    - docker stop $NOME_DO_CONTAINER || true
    - docker rm $NOME_DO_CONTAINER || true
    - docker run --name $NOME_DO_CONTAINER --network $NOME_DA_REDE -p $BIND_DE_PORTA -d $DOCKER_TAG_NAME