
variables:
  APP_PATH: taskmanager_mongodb
  DOCKER_TAG_NAME: $APP_PATH:latest
  NOME_DO_CONTAINER: task_app_container
  NOME_DA_REDE: app-network
  BIND_DE_PORTA: 8080:8080
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SPRING_PROFILES_ACTIVE: "test"
  MONGODB_URI: "mongodb://admin:admin@mongo:27017/workshop_mongo?authSource=admin"

stages:
  - test
  - prebuild
  - build
  - deploy

Unit_Test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  only:
    - dev
  except:
    - main
  artifacts:
    paths:
      - $APP_PATH/target/surefire-reports/
  cache:
    paths:
      - $APP_PATH
  script:
    - cd $APP_PATH
    - mvn test

Clear_Image:
  stage: prebuild
  only:
    - dev
  dependencies: []
  cache: []
  variables:
    GIT_STRATEGY: none
  script:
    - docker conatiner stop $(docker container ls -a ancestor=$DOCKER_TAG_NAME -q) || FAILED=true
    - echo Tentativa de parada de container. Falhou? - $FAILED
    - FAILED=false
    - docker container rm $(docker container ls -a -f ancestor=$DOCKER_TAG_NAME -q) || FAILED=true
    - echo Tentativa de remoção do container. Falhou? - $FAILED
    - FAILED=false
    - docker image rm $DOCKER_TAG_NAME || FAILED=true
    - echo Tentativa de remoção da image. Falhou? - $FAILED

Create_Image:
  stage: build
  only:
    - dev
  dependencies: []
  cache:
    paths:
      - $APP_PATH
  variables:
    GIT_STRATEGY: none
  script:
    - docker build --no-cache -t $DOCKER_TAG_NAME ./$APP_PATH

Create_Container:
  stage: build
  only:
    - dev
  dependencies: []
  cache: []
  variables:
    GIT_STRATEGY: none
  script:
    - docker run --name $NOME_DO_CONTAINER --network $NOME_DA_REDE -p $BIND_DE_PORTA -d $DOCKER_TAG_NAME
