services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network	

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    netwoks:
       - app-network
      
  app:
    container_name: task_app_contianer
    depends_on:
      - mongo
    build:
      context: "./"
      dockerfile: Dockerfile
    working_dir: /usr/src/task
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATA_MONGODB_URI=mongodb://admin:admin@localhost:27017/workshop_mongo?authSource=admin      
    volumes:
      - ./src/:/usr/src/task
    networks:
      - app-network   
     
volumes:
  mongo_data:
  
networks:
  app-network 