apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-mongodb
  template:
    metadata:
      labels:
        app: task-mongodb
    spec:
      containers:
        - name: task-mongodb
          image: gustafcf/task_mongodb:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://admin:admin@mongodb:27017/workshop_mongo?authSource=admin
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: task-mongodb
spec:
  type: LoadBalancer
  selector:
    app: task-mongodb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080